# Generated by Django 4.2.7 on 2025-11-06 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_logs',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('is_audio_transcript', models.BooleanField(default=False)),
                ('is_shared_with_patient', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_notes', models.TextField(blank=True, null=True)),
                ('last_consultation_date', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saved_patients',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_token', models.TextField()),
                ('share_method', models.CharField(choices=[('QR_CODE', 'QR Code'), ('URL', 'Secure URL')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('current_access_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'share_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
