# Generated by Django 4.2.7 on 2025-11-06 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0002_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharetoken',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='share_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharetoken',
            name='records',
            field=models.ManyToManyField(related_name='share_tokens', to='records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='savedpatient',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedpatient',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_doctors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='accessed_records',
            field=models.ManyToManyField(related_name='access_logs', to='records.medicalrecord'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='share_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='sharing.sharetoken'),
        ),
        migrations.AddIndex(
            model_name='sharetoken',
            index=models.Index(fields=['patient', 'is_revoked'], name='share_token_patient_69046f_idx'),
        ),
        migrations.AddIndex(
            model_name='sharetoken',
            index=models.Index(fields=['expires_at'], name='share_token_expires_d66f20_idx'),
        ),
        migrations.AddIndex(
            model_name='savedpatient',
            index=models.Index(fields=['doctor', 'saved_at'], name='saved_patie_doctor__369d65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpatient',
            unique_together={('doctor', 'patient')},
        ),
        migrations.AddIndex(
            model_name='doctornote',
            index=models.Index(fields=['doctor', 'patient', 'created_at'], name='doctor_note_doctor__8804d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['doctor', 'accessed_at'], name='access_logs_doctor__f5d1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='accesslog',
            index=models.Index(fields=['patient', 'accessed_at'], name='access_logs_patient_921ad9_idx'),
        ),
    ]
